---
- hosts: localhost
  vars:
    coltenv: "{{ ansible_env.COLTENV }}"
    username: "{{ ansible_env.COLTE_USER }}"
    mysql_password: "{{ ansible_env.COLTE_DBPASS }}"
    colte_dir: "{{ ansible_env.COLTE_DIR }}"
    crdt_billing_dir: "{{ colte_dir }}/webservices/crdt-billing"

  tasks:
    - name: check for environment vars
      fail: msg="Killing ansible script, environment variables not set! COLTENV = {{ ansible_env.COLTENV }}"
      when: coltenv is not defined

    - name: apt-get update
      apt:
        update_cache: yes
        cache_valid_time: 3600
      become: yes    

# step 1: setup/install mysql db
    - name: apt-get install mysql
      apt:
        name: "{{ item }}"
      become: yes 
      with_items:
      - python-mysqldb
      - mysql-client
      - mysql-server

    - name: mysql configs
      mysql_user:
        name: "{{ username }}"
        password: "{{ mysql_password }}"
        host: localhost
        priv: '*.*:ALL'
        #login_password: research
      become: yes

    - name: install billing table into mysql
      mysql_db:
        login_user: "{{ username }}"
        login_password: "{{ mysql_password }}"
        name: colte_db
        state: import
        target: "{{ crdt_billing_dir }}/customer_db.sql"

    - name: ensure log directory exists
      file:
        path: /var/log/colte
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0755
      become: yes
      